"use strict";
exports.__esModule = true;
var express_1 = require("express");
var SellerController_1 = require("../controllers/SellerController");
var ClientController_1 = require("../controllers/ClientController");
var sellers = new SellerController_1["default"]();
var clients = new ClientController_1["default"]();
var routes = express_1.Router();
routes.get('/sellers', sellers.getAll);
routes.get('/products/:item', clients.getItem);
routes.post('/seller', sellers.newSeller);
routes.post('/client', clients.newClient);
exports["default"] = routes;
